In [1]:
from keras import backend as K
K.tensorflow_backend._get_available_gpus()

Using TensorFlow backend.

['/job:localhost/replica:0/task:0/device:GPU:0']

In [2]:
from pymongo import MongoClient
from bson.objectid import ObjectId

import time,datetime
import os

import pandas as pd
import pandas_datareader.data as web
import numpy as np

import matplotlib.pyplot as plt
from matplotlib import style

from keras.models import Model, Sequential
from keras.layers import Input
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D
import keras

from sklearn import preprocessing

from copy import deepcopy
from IPython.display import clear_output

In [3]:
style.use('ggplot')

In [4]:
conn = MongoClient()
db = conn.Tracker
collection = [db.james]# db.db2, db.dn2, db.james, db.leo
clean_data = []
for col in collection:
    cursor = col.find({})
    df = pd.DataFrame(list(cursor))

In [5]:
df.replace('', np.nan, inplace=True)
df.fillna(method='ffill', inplace=True)
df.isnull().sum().sum()

0

In [6]:
df['hr_value'] = df['hr_value'].astype(float)
df['o2_value'] = df['o2_value'].astype(float)
df['latitude'] = df['latitude'].astype(float)
df['longitude'] = df['longitude'].astype(float)
df['step_value'] = df['step_value'].astype(float)

In [7]:
df['moving_distance'] = np.abs(df.latitude.diff() * 111000) + np.abs(df.longitude.diff() * 110987)

In [8]:
df = df[(df['hr_value'] != 0)]

In [9]:
dfsteptotal = pd.DataFrame()
day = datetime.datetime.fromtimestamp(df['timestamp'].min()).strftime('%d')
month = datetime.datetime.fromtimestamp(df['timestamp'].min()).strftime('%m')
basetime = df['timestamp'].min()
while day != datetime.datetime.fromtimestamp(df['timestamp'].max()).strftime('%d') \
    or month != datetime.datetime.fromtimestamp(df['timestamp'].max()).strftime('%m'):
    df2 = pd.DataFrame({'month': [int(month)], 'day': [int(day)], 'morning':0, 'afternoon':0, 'evening':0})
    dfsteptotal = dfsteptotal.append(df2, ignore_index=True)
    basetime = (datetime.datetime.fromtimestamp(basetime) + datetime.timedelta(days=1)).timestamp()
    day = datetime.datetime.fromtimestamp(basetime).strftime('%d')
    month = datetime.datetime.fromtimestamp(basetime).strftime('%m')
df2 = pd.DataFrame({'month': [int(month)], 'day': [int(day)], 'morning':0, 'afternoon':0, 'evening':0})
dfsteptotal = dfsteptotal.append(df2, ignore_index=True)
dfsteptotal = dfsteptotal.set_index(['month', 'day'])
# dfsteptotal

In [10]:
# here I map between integer and the sting it's mean
timeslidemap = {0:'morning', 1:'afternoon', 2:'evening'}
basestamp = df['timestamp'][0]
endstamp = df['timestamp'][-1:].values[0]
# for num, row in df[:30000].iterrows():
while True:
    # here I write to devide time into 3 part where estimedevide will tell me basetime will be at
    estimedevide = int(int(datetime.datetime.fromtimestamp(basestamp).strftime('%H')) / 8)
#     print(estimedevide)
#     while estimedevide[0] != estimedevide[1]:
    hourend = 8*estimedevide + 7
    # know where the part the day is
#     print(int(datetime.datetime.fromtimestamp(basestamp).strftime('%H')), hourend)
    dfbetween = df.loc[df['timestamp'].between(basestamp,datetime.datetime.fromtimestamp(basestamp).replace(
                hour=hourend,minute=59,second=59).timestamp(), inclusive=True)]
    steps = dfbetween['step_value'].sum()
#     print(int(datetime.datetime.fromtimestamp(basestamp).strftime('%m')),
#             int(datetime.datetime.fromtimestamp(basestamp).strftime('%d')),
#                 timeslidemap[estimedevide])

    dfsteptotal.loc[[(int(datetime.datetime.fromtimestamp(basestamp).strftime('%m')),
                        int(datetime.datetime.fromtimestamp(basestamp).strftime('%d')))], 
                           [timeslidemap[estimedevide]]] += steps

    # These line are for debug whether steps are equal to dfsteptotal step's value
#     print('inspection', steps, '\n', dfsteptotal.loc[[(datetime.datetime.fromtimestamp(basestamp).isocalendar()[1] - 
#             (datetime.datetime.fromtimestamp(basestamp).isoweekday() < 7),
#                 datetime.datetime.fromtimestamp(basestamp).strftime('%w'))],[timeslidemap[estimedevide]]])
#     break
#     print(basestamp, endstamp)

    # next 8 hours of time
    basestamp = (datetime.datetime.fromtimestamp(basestamp) + datetime.timedelta(hours=8)).timestamp()
    if basestamp > endstamp:
        break
#     else:
#         print(datetime.datetime.fromtimestamp(basestamp) ,datetime.datetime.fromtimestamp(endstamp))

In [11]:
# dfsteptotal.loc[(dfsteptotal['morning'] == 0),['morning']]= int(dfsteptotal['morning'].mean())
dfsteptotal.loc[(dfsteptotal['afternoon'] == 0),['afternoon']]= int(dfsteptotal['afternoon'].mean())
dfsteptotal.loc[(dfsteptotal['evening'] == 0),['evening']]= int(dfsteptotal['evening'].mean())
# dfsteptotal[dfsteptotal['evening'] == 0]['evening'] = int(dfsteptotal['evening'].mean())

In [12]:
dfsteptotal

           morning  afternoon  evening
month day
3     27       0.0     2811.0   2366.0
      28       0.0     2104.0   1692.0
      29       0.0     2811.0   1692.0
      30       0.0     1878.0     73.0
      31     320.0      454.0    367.0
4     1        0.0     6587.0   2145.0
      2      248.0     3702.0   1444.0
      3        0.0     1964.0   3793.0
      4      499.0     3090.0   1854.0
      5      318.0     2084.0   1471.0
      6        0.0     2051.0   1353.0
      7      692.0     2506.0   5639.0
      8      289.0     3269.0   1581.0
      9        0.0      229.0   3903.0
      10       0.0     3989.0    744.0
      11       0.0     1879.0    434.0
      12      91.0     3568.0    480.0
      13    1391.0     3726.0    256.0
      14     229.0     4427.0   1918.0
      15    1111.0     7476.0   2890.0
      16       0.0     1629.0   2850.0
      17     298.0     4275.0   2433.0
      18     342.0     4088.0   2814.0
      19     327.0     2870.0   1638.0
      20      53.0     5175.0   1561.0
      21     300.0       71.0   1692.0

In [17]:
# add wether 
coding = 'utf-8'
for index, row in dfsteptotal.iterrows():
    # parsing part
    date = datetime.date(2019,index[0],index[1])
    dateStr = date.strftime('%Y-%m-%d')
    url = 'https://e-service.cwb.gov.tw/HistoryDataQuery/DayDataController.do?command=viewMain&station=C0AC60'+
        '&stname=%25E4%25B8%2589%25E5%25B3%25BD&datepicker=' + dateStr
    table = pd.read_html(url,encoding=coding,index_col=0,header=None,flavor='bs4')[1]
    # start dataprocess
    table.replace('/', np.nan, inplace=True)
    table.fillna(method='ffill', inplace=True)
    table.index -= 1
    dfoneday = pd.DataFrame()
    # the table data need to reshape and turn to a variable
    T = table['temperature'].values.reshape(len(table['temperature'].values)).astype('float')
    RH = table['RH'].values.reshape(len(table['RH'].values)).astype('float')
    dfoneday['comfort'] = T - 0.55 *(1-RH/100)*(T - 14)
    dfoneday['Precp'] = table['Precp']['降水量(mm)']
    dfsteptotal.loc[[index]]`
    break

(3, 27)
2019-03-27

In [145]:
# split a multivariate sequence into samples
def split_sequences(sequences, n_steps):
    X, y = list(), list()
    for i in range(len(sequences[0])):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the dataset
        if end_ix > len(sequences[0])-1:
            break
        # gather input and output parts of the pattern
        seq_x = sequences[0][i:end_ix].reshape(len(sequences[0][i:end_ix]),1) 
        seq_x = np.append(seq_x, sequences[1][i:end_ix].reshape(len(sequences[1][i:end_ix]),1), axis=1)
        seq_y1, seq_y2 =  sequences[0][end_ix] ,sequences[1][end_ix]
        X.append(seq_x)
        y.append([seq_y1,seq_y2])
    return np.array(X), np.array(y)

In [146]:
# this split will predict next value
in_seq1 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = np.array([15, 25, 35, 45, 55, 65, 75, 85, 95])
dataset = np.array([in_seq1, in_seq2])
n_steps = 3
X, y = split_sequences(dataset, n_steps)
for i in range(len(X)):
    print(X[i], y[i])

[[10 15]
 [20 25]
 [30 35]] [40 45]
[[20 25]
 [30 35]
 [40 45]] [50 55]
[[30 35]
 [40 45]
 [50 55]] [60 65]
[[40 45]
 [50 55]
 [60 65]] [70 75]
[[50 55]
 [60 65]
 [70 75]] [80 85]
[[60 65]
 [70 75]
 [80 85]] [90 95]